export type AddressDetailType = {
  PK: string;
  AddressType: string;
  JDAOADAddressFK: string;
  Contact: string;
  AddressOverride: string | null;
  CompanyName: string;
  Address1: string;
  Address2: string;
  City: string;
  Postcode: string;
  State: string;
  CountryCode: string;
  Phone: string;
  Fax: string;
  Email: string;
  EntityRefKey: string;
  EntitySource: string;
  Mobile: string | null;
  IsValid: boolean | null;
  AddressSequence: number;
  GovRegNum: string | null;
  IsResidential: boolean | null;
  GovRegNumType: string | null;
  ScreeningStatus: string | null;
  Source: string | null;
  JDAORGFK: string;
  JDAOCTFK: string;
  JDAORGCode: string;
  JDAOADCode: string;
  PhoneExtension: string | null;
  HomePhone: string | null;
  OtherPhone: string | null;
  Latitude: number | null;
  Longtitude: number | null;
  CountryCodeDesc: string;
  StateDesc: string;
  SiteId: string | null;
  ExternalSiteId: string | null;
  SiteName: string | null;
  SiteNameId: string | null;
  ModifiedDateTime: string | null;
  ModifiedBy: string | null;
  OAD_Code: string | null;
  OAD_Name: string | null;
  RN_NKCountryCode: string | null;
}
