export type BookingType = {
    SHPPK: string; // SHPPK
    Status: string;
    BookingNo: string;
    HouseBill: string | null;
    BookedDate: string;
    GoodsDesc: string | null;
    ReleaseType: string | null;
    BookingType: string;
    Origin: string;
    ETD: string | null;
    ATD: string | null;
    Destination: string;
    PrepaidCollect: string;
    ETA: string | null;
    ATA: string | null;
    IncoTerm: string;
    TransportMode: string;
    PackingMode: string;
    Volume: number;
    UnitOfVolume: string | null;
    Weight: number;
    UnitOfWeight: string | null;
    Chargeable: number;
    InnerPackCount: number;
    OuterPackCount: number;
    HouseBillType: string | null;
    InnerPackType: string | null;
    OuterPackType: string | null;
    ConsigneeFK: string;
    ShipperFK: string;
    ConsigneeCode: string;
    ConsigneeName: string;
    ShipperName: string;
    InvoiceRefNo: string | null;
    ScreeningStatus: string | null;
    TenantCode: string;
    SharedRoleCode: string;
    EntityType: string;
    BookingDirection: string;
    CustomsClearanceDate: string | null;
    ControlCustomCode: string | null;
    DeliveryToName: string;
    OriginName: string;
    Containers: any; // Could be better typed if structure known
    OrderNos: string | null;
    DeliveryStatus: string;
    DestinationName: string | null;
    ControlCustomFK: string | null;
    StatusDesc: string;
    ContainerNo: string | null;
    BookingApprovedDate: string | null;
    ExportBy: string | null;
    ProductName: string | null;
    ProductSize: string | null;
    NetWeight: number;
    BookingSubmittedDate: string | null;
    ImportBy: string | null;
    Remarks: string | null;
    CancelledDate: string | null;
    CompletedDate: string | null;
    CargoReceiptDate: string | null;
    ImportCustomClearanceCompletedDate: string | null;
    EstimatedDelivery: string | null;
    IsBroker: boolean;
    DeclarationEntryNO: string | null;
    EmptyReturnReadyOn: string | null;
    DeliveryCartageCompleted: string | null;
    DeclarationEntryStatus: string | null;
    EmptyCartageCompleted: string | null;
    StateId: number;
    IsValid: boolean;
    SHP_IsBooking: boolean;
  }
  