export type RoutingType = {
    PK: string;
    TransportMode: string;
    LegOrder: number;
    TransportType: string;
    Vessel: string;
    VoyageFlight: string;
    IsLinked: boolean;
    LoadPort: string;
    ETD: string;
    ATD: string;
    DischargePort: string;
    ETA: string;
    ATA: string;
    CarrierReference: string | null;
    EntitySource: string;
    EntityRefKey: string;
    TruckType: string | null;
    Status: string;
    IsValid: boolean;
    CreatedBy: string;
    CreatedDateTime: string;
    ModifiedBy: string;
    ModifiedDateTime: string;
    StateId: number;
    Source: string | null;
    DepartureLocationOrg_Code: string | null;
    DepartureLocationOrg_FK: string | null;
    DepartureLocation_OAD_FK: string | null;
    ArrivalLocationOrg_Code: string | null;
    ArrivalLocationOrg_FK: string | null;
    ArrivalLocation_OAD_FK: string | null;
    CarrierOrg_Code: string;
    CarrierOrg_FK: string;
    Carrier_OAD_FK: string | null;
    CreditorOrg_Code: string | null;
    CreditorOrg_FK: string | null;
    Creditor_OAD_FK: string | null;
    IsModified: boolean;
    IsDeleted: boolean;
    JobNo: string;
    JBS_FK: string | null;
    CargoCutOffDate: string | null;
    BookingCutOffDate: string | null;
    DocumentCutOffDate: string | null;
    ExpiryDate: string | null;
    TenantCode: string;
    CarrierName: string;
    LlyodsNo: string;
    LoadPortDesc: string;
    DischargePortDesc: string;
    CountryDescOfLoadPort: string | null;
    CountryDescOfDischargePort: string | null;
    VGMCutOffDate: string | null;
    SnoozedDateTime: string | null;
    IsSnoozed: boolean;
    TrackingStatus: string | null;
    MovementStatus: string | null;
    LogCount: number | null;
    ShipmentCount: number | null;
    ShipmentNos: string | null;
    ConsigneeCode: string | null;
    ConsignorCode: string | null;
    Comments: string | null;
    CommentValue: string | null;
    OriginalETD: string | null;
    OriginalETA: string | null;
    CON_ConsolNo: string | null;
    IsETAError: number;
    POLTimeZoneSetName: string;
    PODTimeZoneSetName: string;
    MasterBillNo: string | null;
    ContainerNos: string | null;
    HouseBillNos: string | null;
    CountryOfOrigin: string | null;
    CountryOfDestination: string | null;
    ShippedOnBoardDate: string | null;
    CarrierCode: string | null;
    VesselName: string | null;
    UploadDocument: any;
    Save: any;
    CommentHistory: any;
    FlightETA: string | null;
    LegDescription: string | null;
    EventStatus: string | null;
    LastTrackBy: string | null;
    LastTrackDate: string | null;
    NextTrackDate: string | null;
    TaskName: string | null;
    DueDate: string | null;
    TaskStatus: string | null;
  }
  