export type TaskType = {
    PK: string;
    WorkItemNo: number;
    PSM_FK: string;
    PSI_FK: string;
    PSI_InstanceNo: number;
    WSI_StepCode: string;
    WSI_StepDescription: string;
    WSI_CompletedStepName: string | null;
    Orchestrator: string;
    LoopNo: number;
    Status: string;
    Performer: string;
    PrePerformer: string | null;
    AvailableDate: string;
    AssignedDate: string | null;
    EndDate: string | null;
    DueDate: string;
    Snooze: string | null;
    OrderbyDate: string | null;
    Duration: string | null;
    EntitySource: string;
    EntityRefKey: string;
    KeyReference: string;
    SRO_Code: string | null;
    IsCompanyBased: boolean;
    CMPCode: string;
    BRNCode: string;
    IsBranchBased: boolean;
    DEP_Code: string | null;
    IsDepartmentBased: boolean;
    WAR_Code: string | null;
    IsWarehouseBased: boolean;
    ORGCode: string | null;
    IsOrganisationBased: boolean;
    Custom_CodeI: string;
    IsCustomIBased: boolean;
    Custom_CodeII: string;
    IsCustomIIBased: boolean;
    Custom_CodeIII: string;
    IsCustomIIIBased: boolean;
    IsActive: boolean;
    CreatedBy: string;
    CreatedDateTime: string;
    ModifiedBy: string;
    ModifiedDateTime: string;
    SAP_FK: string | null;
    TenantCode: string;
    IsModified: boolean;
    IsDeleted: boolean;
    INITRules: string | null;
    CompleteRules: string | null;
    WSI_FK: string;
    WSI_StepNo: number;
    WSI_StepType: string;
    WSIStepName: string;
    AmIWaiting: boolean | null;
    WaitingMode: string | null;
    EBPMInputs: string | null;
    KPIDescription: string | null;
    ProcessName: string;
    UserStatus: string;
    Task_KPIStatus: string | null;
    EntityInfo: string | null;
    InstanceInfo: string | null;
    Delay: number;
    UserName: string | null;
    AccessMode: string;
    RelatedProcess: string | null;
    OtherConfig: string;
    TMP_PK: string;
    ParentEntityRefKey: string | null;
    ParentEntitySource: string | null;
    ParentEntityRefCode: string | null;
    AdditionalEntityRefKey: string | null;
    AdditionalEntitySource: string | null;
    AdditionalEntityRefCode: string | null;
    IsReAssignToRequestor: boolean;
    WorkStartTime: string;
    DelayReasonCode: string | null;
    Requester: string | null;
    IsWorkStartEnabled: boolean;
    IsWorkStarted: boolean;
    DisplayOrder: number | null;
    LevelNo: number;
    WSR_ActionType: string | null;
    ProcessCode: string | null;
    ParentProcessCode: string | null;
    RootPath: string | null;
    ListingPageName: string;
    RelatedOutput: string | null;
    IsWorkStartedStr: string;
    IsWorkStartEnabledStr: string;
    IsRoleBased: boolean;
    RelatedInput: string | null;
    SharedEntityInput: string | null;
    PerformerCode: string;
    IsQueueLogEnabled: boolean;
    Custom_CodeIV: string;
    Custom_CodeV: string;
    Custom_CodeVI: string | null;
    CustomCodeVII: string;
    CustomCodeVIII: string;
    Custom_CodeIX: string | null;
    CustomCodeX: string | null;
    Custom_CodeXI: string | null;
    Custom_CodeXII: string | null;
    IsCustomIVBased: boolean;
    IsCustomVBased: boolean;
    IsCustomVIBased: boolean;
    IsCustomVIIBased: boolean;
    IsCustomVIIIBased: boolean;
    IsCustomIXBased: boolean;
    IsCustomXBased: boolean;
    IsCustomXIBased: boolean;
    IsCustomXIIBased: boolean;
    WSA_EntitySourceName: string;
    WSA_DirectAssignMode: string | null;
    StartDate: string;
    RolesListfromGroup: string | null;
    IsNextTaskInitated: boolean;
    IsEndTask: boolean;
    IsTaskCompleted: boolean;
    RuleMode: string | null;
    TAT: number;
    CMP_Code?  : string | null;
    BRN_Code?  : string | null;
    ORG_Code?  : string | null;
    WSI_StepName: string | null;
    Custom_CodeVII: string | null;
    Custom_CodeVIII: string | null;
    Custom_CodeX: string | null;
}