import { AddressDetailType } from "@/types/address.types";

export const AddressData: AddressDetailType[] = [{
    Address1: "Second Floor, Sree Vihar Complex,",
    City: "Girgaon",
    CompanyName: "Zest & Green Marketing Agency,",
    AddressType: "CED",
    ModifiedDateTime: "2025-03-19T07:02:54.853",
    ModifiedBy: "ldasarathana@20cube.com",
    OAD_Code: "Second Floor, Sree Vihar Complex,",
    Postcode: "400004",
    RN_NKCountryCode: "IN",
    State: "Mumbai",
    Email: "contact@zestgreen.com",
    Phone: "+91 22 12345678",
    PK: "",
    JDAOADAddressFK: "",
    Contact: "",
    AddressOverride: null,
    Address2: "",
    CountryCode: "",
    Fax: "",
    EntityRefKey: "",
    EntitySource: "",
    Mobile: null,
    IsValid: null,
    AddressSequence: 0,
    GovRegNum: null,
    IsResidential: null,
    GovRegNumType: null,
    ScreeningStatus: null,
    Source: null,
    JDAORGFK: "",
    JDAOCTFK: "",
    JDAORGCode: "",
    JDAOADCode: "",
    PhoneExtension: null,
    HomePhone: null,
    OtherPhone: null,
    Latitude: null,
    Longtitude: null,
    CountryCodeDesc: "",
    StateDesc: "",
    SiteId: null,
    ExternalSiteId: null,
    SiteName: null,
    SiteNameId: null,
    OAD_Name: null
},
{
    Address1: "Second Floor, Sree Vihar Complex,",
    City: "Girgaon",
    CompanyName: "Zest & Green Marketing Agency,",
    AddressType: "CED",
    ModifiedDateTime: "2025-03-19T07:02:54.853",
    ModifiedBy: "ldasarathana@20cube.com",
    OAD_Code: "Second Floor, Sree Vihar Complex,",
    Postcode: "400004",
    RN_NKCountryCode: "IN",
    State: "Mumbai",
    Email: "contact@zestgreen.com",
    Phone: "+91 22 12345678",
    PK: "",
    JDAOADAddressFK: "",
    Contact: "",
    AddressOverride: null,
    Address2: "",
    CountryCode: "",
    Fax: "",
    EntityRefKey: "",
    EntitySource: "",
    Mobile: null,
    IsValid: null,
    AddressSequence: 0,
    GovRegNum: null,
    IsResidential: null,
    GovRegNumType: null,
    ScreeningStatus: null,
    Source: null,
    JDAORGFK: "",
    JDAOCTFK: "",
    JDAORGCode: "",
    JDAOADCode: "",
    PhoneExtension: null,
    HomePhone: null,
    OtherPhone: null,
    Latitude: null,
    Longtitude: null,
    CountryCodeDesc: "",
    StateDesc: "",
    SiteId: null,
    ExternalSiteId: null,
    SiteName: null,
    SiteNameId: null,
    OAD_Name: null
}];