import { Book, Order } from "@/types/order.types";

export const Orders: Order[] = [
  {
      "PK": "8afa934d-6881-426d-b51c-5dd09f041695",
      "IsValid": true,
      "IsCancelled": false,
      "ORG_Buyer_FK": "c083c734-d2a6-463a-a01d-22b3b01db416",
      "Buyer": "000010070000",
      "BuyerName": "Zest & Green Marketing Agency,",
      "OrderNo": "Hello",
      "FollowUpId": "",
      "PreAdviceId": "",
      "OrderNoSplit": 0,
      "OrderCumSplitNo": "Hello",
      "OrderDate": "2025-02-12T00:00:00",
      "ShpCreatedDate": "2025-01-10T06:03:54.217",
      "OrderStatus": "BOC",
      "GoodsDescription": null,
      "TransportMode": "SEA",
      "ContainerMode": "FCL",
      "ORG_Supplier_FK": "1f2edc90-f552-4547-9e41-a02bc0046bd1",
      "Supplier": "DEMBUYMAA",
      "SupplierName": "DEMBUYMAA",
      "ConfirmNo": "",
      "ConfirmDate": null,
      "FollowUpDate": null,
      "CargoReadyDate": "2025-01-10T00:00:00",
      "RequiredExWorksDate": null,
      "RequiredDeliveryDate": null,
      "InvoiceNo": null,
      "InvoiceDate": null,
      "ExchangeRate": 0,
      "ServiceLevel": null,
      "IncoTerm": "CIF",
      "AdditionalTerms": null,
      "ActualVolume": 0,
      "UnitOfVolume": null,
      "ActualWeight": 0,
      "UnitofWeight": null,
      "Packs": 0,
      "OrderPackType": null,
      "EstimatedExWorksDate": null,
      "EstimatedInStoreDate": null,
      "SHP_FK": "f6b71b64-cc94-4268-99df-613e99279aea",
      "ShipmentNo": "SHP00183339",
      "BRK_FK": null,
      "WayBill": null,
      "MasterWaybill": "987659876",
      "JDA_DeliveryAdress": null,
      "ORA_DeliveryAdress": null,
      "ORG_Carrier_FK": null,
      "CarrierCode": "OBMINTBNE",
      "CarrierName": "",
      "ORG_SendingAgent_FK": "416dcf62-bd31-4dca-b3a0-d1c45881f740",
      "ORG_ReceivingAgent_FK": null,
      "ArrivalVoyage": null,
      "GoodsAvailableAt": "INMAA",
      "GoodsAvailableAtDes": "Chennai (ex Madras)",
      "PortOfLoading": "INMAA",
      "PortOfLoadingDes": "Chennai (ex Madras)",
      "PortOfDischarge": "LKCMB",
      "PortOfDischargeDes": "Colombo",
      "GoodsDeliveredTo": "LKCMB",
      "GoodsDeliveredToDes": "Colombo",
      "DepartureVessel": null,
      "DepartureVoyage": null,
      "DepartureVesselCutoffDate": null,
      "IntermediateVessel": null,
      "IntermediateVoyage": null,
      "ArrivalVessel": null,
      "ArrivalIntermediateDate2": null,
      "ArrivalIntermediateDate1": null,
      "EstimatedDepartureDate2": null,
      "EstimatedDepartureDate3": null,
      "EstimatedRecievedDate": null,
      "EstimatedDepartureDate": null,
      "EstimatedArrivalDate": null,
      "EstimatedClearanceCommencedDate": null,
      "EstimatedClearanceFinalizedDate": null,
      "EstimatedUnpackedDate": null,
      "EstimatedPickUp": null,
      "ActualExFactoryDate": null,
      "ActualRecievedDate": null,
      "ActualDepartureDate": null,
      "ActualClearanceCommencedDate": null,
      "ActualArrivalDate": null,
      "ActualClearanceFinalizedDate": null,
      "ActualUnpackedDate": null,
      "ActualPickup": null,
      "ActualInStoreDate": null,
      "OriginCountry": "IN",
      "OrderCurrency": null,
      "ContainerPackType": null,
      "PlannedETD": null,
      "PlannedETA": null,
      "PlannedATD": null,
      "PlannedATA": null,
      "PlannedVessel": null,
      "PlannedVoyage": null,
      "PlannedCarrier": null,
      "ETD": "2023-09-05T00:00:00",
      "ETA": "2023-09-28T00:00:00",
      "ATA": null,
      "ATD": null,
      "Vessel": "test",
      "Voyage": "tesr",
      "Carrier": null,
      "CreatedBy": "ldasarathana@20cube.com",
      "CreatedDateTime": "2025-02-12T06:21:44.323",
      "ModifiedBy": "jprakash@20cube.com",
      "ModifiedDateTime": "2025-03-20T06:31:37.443",
      "StateId": 1080,
      "Source": null,
      "SourceRefKey": null,
      "IsModified": false,
      "IsDeleted": false,
      "Version": null,
      "OrderParentId": null,
      "Communication": null,
      "IsStarred": false,
      "Starred_FK": null,
      "IsShpCreated": true,
      "IsFollowUpIdCreated": false,
      "IsPreAdviceIdCreated": false,
      "POB_FK": null,
      "CustomDate1": null,
      "CustomDate2": null,
      "SendingAgentCode": "OMEGLOMAA",
      "ReceivingAgentCode": null,
      "BatchUploadNo": null,
      "CMN_TenantCode": "20CUB",
      "CMN_SharedRoleCode": "3_3",
      "JBS_FK": null,
      "CRT_FK": null,
      "PCFS": null,
      "DCFS": null,
      "Comments": null,
      "ExpectedCargoReadyDate": null,
      "OrderStatusDesc": "Order Booked for Shipment",
      "Status": "",
      "OrderHeaderExtendedPK": null,
      "PAR_ORG_FK": "f2bc1245-80b5-4c8f-9025-0766dacfc32d",
      "PAR_ORG_Code": "20CUBCORP",
      "ORG_ControlCustom_FK": null,
      "ControlCustomCode": null,
      "IsConfirmReqSent": true,
      "PartyType_Code": "FORWARDER",
      "PartyType_FK": "52af4aef-882a-4ae8-990d-4c81d03dfae8",
      "PAR_AccessCode": "3_3",
      "FollowUpSentDate": null,
      "HandoverDate": null,
      "FOBDate": null,
      "ETDPlant": null,
      "FactoryInvoiceNo": null,
      "FactoryPKLNo": null,
      "ImportCHA_Code": null,
      "ExportCHA_Code": null,
      "ExportCHA_FK": null,
      "ImportCHA_FK": null,
      "BuyingHouseAgent_FK": null,
      "BuyingHouseAgent_Code": null,
      "IsFollowUpMailSent": false,
      "IsPreadviceMailSent": false,
      "PartyTenantCode": null,
      "SharedRoleCode": null,
      "ConsigneeName": "Zest & Green Marketing Agency,",
      "ConsignorName": "DEMBUYMAA",
      "ORG_CarrierName": "20CUBE LOGISTICS PTY LTD",
      "ORG_SendingAgentName": "20CUBE LOGISTICS SOLUTIONS PRIVATE LIMITED1",
      "ORG_ReceivingAgentName": null,
      "ORG_ControlCustomName": null,
      "ExportCHAName": null,
      "ImportCHAName": null,
      "BuyingHouseAgentName": null,
      "WHCode": null,
      "WHName": null,
      "OrderType": "POR",
      "CustomVarI": null,
      "CustomVarII": null,
      "CustomVarIII": null,
      "CustomVarIV": null,
      "CustomVarV": null,
      "JCT_FK": null,
      "IsBooked": false,
      "OrderPlacedDate": null,
      "CargoReadyDateRequestedDate": null,
      "CargoReadyDateReceivedDate": null,
      "VesselPlanRequestedDate": null,
      "VesselPlanReceivedDate": null,
      "BookedDate": "2025-02-12T06:22:14.257",
      "PlannedCarrierPK": null,
      "PlannedCarrierCode": null,
      "PlannedCarrierName": null,
      "PlannedVesselName": null,
      "PlannedVesselPK": null,
      "PlannedPOL": null,
      "PlannedPOLDesc": null,
      "PlannedPODDesc": null,
      "PlannedPOD": null,
      "PlannedCargoCutOff": null,
      "PlannedBookingCutOff": null,
      "DocumentCutOff": null,
      "CargoReadyDateInitiatedDate": null,
      "SFH_FK": null,
      "FollowUpRefNo": null,
      "PPH_FK": null,
      "PlanningRefNo": null,
      "ContainerNo": null,
      "OriginBranch_FK": "3a77cbf5-d626-4c62-9c30-0392356c9a2f",
      "OriginBranchCode": "MAA",
      "OriginCompany_FK": "58a3ede2-e616-4651-a8ef-7fc311b9fced",
      "OriginCompanyCode": "MAA",
      "DestinationBranch_FK": "32b16ce6-126f-4042-b0d4-d67469d6c61e",
      "DestinationBranchCode": "CMB",
      "DestinationCompany_FK": "25e56ecb-f131-4459-97f1-129705df83ee",
      "DestinationCompanyCode": "CMB",
      "Forwarder_ORG_FK": "f2bc1245-80b5-4c8f-9025-0766dacfc32d",
      "Forwarder_ORG_Code": "20CUBCORP",
      "UIJobAddress": null,
      "UIOrderLine_Forwarder": null,
      "SailingCutoffDate": null,
      "UICustomEntity": null,
      "OrderApprovedDate": null,
      "OrderRejectedDate": null,
      "OrderApprovedRejectedComments": null,
      "ExportForwarder_FK": "416dcf62-bd31-4dca-b3a0-d1c45881f740",
      "ExportForwarder_Code": "OMEGLOMAA",
      "ExportForwarderName": "20CUBE LOGISTICS SOLUTIONS PRIVATE LIMITED1",
      "ImportForwarder_FK": "cd4dac8d-d149-42ef-8e1a-162c9fbf01ae",
      "ImportForwarder_Code": "CLSCONCMB",
      "ImportForwarderName": "20CUBE LOGISTICS (PVT) LTD",
      "OrderApprovalRequestedDate": null,
      "ExportBy": "BRN",
      "ImportBy": "BRN",
      "Origin": null,
      "Destination": null,
      "CountryOfDestination": "LK",
      "CountryOfOrigin": "IN",
      "TraderName": null,
      "TraderCode": null,
      "ORG_Trader_FK": null,
      "SHP_Origin": "INMAA",
      "SHP_Destination": "LKCMB",
      "SHP_OriginName": "Chennai (ex Madras)",
      "SHP_DestinationName": "Colombo",
      "ShipmentStatus": "Sent for Approval",
      "JCT_CustomDecimalI": null,
      "JCT_CustomDecimalII": null,
      "CargoReceiptDate": null,
      "AttachedToBooking": null,
      "CancelledOn": null,
      "CustomGuidI": null,
      "CustomDateI": null,
      "CustomDateII": null,
      "CustomDateIII": null,
      "CustomBitI": false,
      "CustomBitII": false,
      "IsActive": true,
      "OrderLine": [
          {"id":"1", "name":"Palani", "value":"3"}
      ]
  },
  {
      "PK": "aaffb259-62c0-4171-b5dc-4984de8aed18",
      "IsValid": true,
      "IsCancelled": false,
      "ORG_Buyer_FK": "c083c734-d2a6-463a-a01d-22b3b01db416",
      "Buyer": "000010070000",
      "BuyerName": "Zest & Green Marketing Agency,",
      "OrderNo": "Lingeyuei",
      "FollowUpId": "",
      "PreAdviceId": "",
      "OrderNoSplit": 0,
      "OrderCumSplitNo": "Lingeyuei",
      "OrderDate": "2025-02-12T00:00:00",
      "ShpCreatedDate": "2025-01-10T06:03:54.217",
      "OrderStatus": "BOC",
      "GoodsDescription": null,
      "TransportMode": "SEA",
      "ContainerMode": "FCL",
      "ORG_Supplier_FK": "1f2edc90-f552-4547-9e41-a02bc0046bd1",
      "Supplier": "DEMBUYMAA",
      "SupplierName": "DEMBUYMAA",
      "ConfirmNo": "",
      "ConfirmDate": null,
      "FollowUpDate": null,
      "CargoReadyDate": "2025-01-10T00:00:00",
      "RequiredExWorksDate": null,
      "RequiredDeliveryDate": null,
      "InvoiceNo": null,
      "InvoiceDate": null,
      "ExchangeRate": 0,
      "ServiceLevel": null,
      "IncoTerm": "CIF",
      "AdditionalTerms": null,
      "ActualVolume": 0,
      "UnitOfVolume": null,
      "ActualWeight": 0,
      "UnitofWeight": null,
      "Packs": 0,
      "OrderPackType": null,
      "EstimatedExWorksDate": null,
      "EstimatedInStoreDate": null,
      "SHP_FK": "f6b71b64-cc94-4268-99df-613e99279aea",
      "ShipmentNo": "SHP00183339",
      "BRK_FK": null,
      "WayBill": null,
      "MasterWaybill": "987659876",
      "JDA_DeliveryAdress": null,
      "ORA_DeliveryAdress": null,
      "ORG_Carrier_FK": null,
      "CarrierCode": "OBMINTBNE",
      "CarrierName": "",
      "ORG_SendingAgent_FK": "416dcf62-bd31-4dca-b3a0-d1c45881f740",
      "ORG_ReceivingAgent_FK": null,
      "ArrivalVoyage": null,
      "GoodsAvailableAt": "INMAA",
      "GoodsAvailableAtDes": "Chennai (ex Madras)",
      "PortOfLoading": "INMAA",
      "PortOfLoadingDes": "Chennai (ex Madras)",
      "PortOfDischarge": "LKCMB",
      "PortOfDischargeDes": "Colombo",
      "GoodsDeliveredTo": "LKCMB",
      "GoodsDeliveredToDes": "Colombo",
      "DepartureVessel": null,
      "DepartureVoyage": null,
      "DepartureVesselCutoffDate": null,
      "IntermediateVessel": null,
      "IntermediateVoyage": null,
      "ArrivalVessel": null,
      "ArrivalIntermediateDate2": null,
      "ArrivalIntermediateDate1": null,
      "EstimatedDepartureDate2": null,
      "EstimatedDepartureDate3": null,
      "EstimatedRecievedDate": null,
      "EstimatedDepartureDate": null,
      "EstimatedArrivalDate": null,
      "EstimatedClearanceCommencedDate": null,
      "EstimatedClearanceFinalizedDate": null,
      "EstimatedUnpackedDate": null,
      "EstimatedPickUp": null,
      "ActualExFactoryDate": null,
      "ActualRecievedDate": null,
      "ActualDepartureDate": null,
      "ActualClearanceCommencedDate": null,
      "ActualArrivalDate": null,
      "ActualClearanceFinalizedDate": null,
      "ActualUnpackedDate": null,
      "ActualPickup": null,
      "ActualInStoreDate": null,
      "OriginCountry": "IN",
      "OrderCurrency": null,
      "ContainerPackType": null,
      "PlannedETD": null,
      "PlannedETA": null,
      "PlannedATD": null,
      "PlannedATA": null,
      "PlannedVessel": null,
      "PlannedVoyage": null,
      "PlannedCarrier": null,
      "ETD": "2023-09-05T00:00:00",
      "ETA": "2023-09-28T00:00:00",
      "ATA": null,
      "ATD": null,
      "Vessel": "test",
      "Voyage": "tesr",
      "Carrier": null,
      "CreatedBy": "ldasarathana@20cube.com",
      "CreatedDateTime": "2025-02-12T06:23:06.753",
      "ModifiedBy": "jprakash@20cube.com",
      "ModifiedDateTime": "2025-03-20T06:31:35.527",
      "StateId": 1080,
      "Source": null,
      "SourceRefKey": null,
      "IsModified": false,
      "IsDeleted": false,
      "Version": null,
      "OrderParentId": null,
      "Communication": null,
      "IsStarred": false,
      "Starred_FK": null,
      "IsShpCreated": true,
      "IsFollowUpIdCreated": false,
      "IsPreAdviceIdCreated": false,
      "POB_FK": null,
      "CustomDate1": null,
      "CustomDate2": null,
      "SendingAgentCode": "OMEGLOMAA",
      "ReceivingAgentCode": null,
      "BatchUploadNo": null,
      "CMN_TenantCode": "20CUB",
      "CMN_SharedRoleCode": "3_3",
      "JBS_FK": null,
      "CRT_FK": null,
      "PCFS": null,
      "DCFS": null,
      "Comments": null,
      "ExpectedCargoReadyDate": null,
      "OrderStatusDesc": "Order Booked for Shipment",
      "Status": "",
      "OrderHeaderExtendedPK": null,
      "PAR_ORG_FK": "f2bc1245-80b5-4c8f-9025-0766dacfc32d",
      "PAR_ORG_Code": "20CUBCORP",
      "ORG_ControlCustom_FK": null,
      "ControlCustomCode": null,
      "IsConfirmReqSent": true,
      "PartyType_Code": "FORWARDER",
      "PartyType_FK": "52af4aef-882a-4ae8-990d-4c81d03dfae8",
      "PAR_AccessCode": "3_3",
      "FollowUpSentDate": null,
      "HandoverDate": null,
      "FOBDate": null,
      "ETDPlant": null,
      "FactoryInvoiceNo": null,
      "FactoryPKLNo": null,
      "ImportCHA_Code": null,
      "ExportCHA_Code": null,
      "ExportCHA_FK": null,
      "ImportCHA_FK": null,
      "BuyingHouseAgent_FK": null,
      "BuyingHouseAgent_Code": null,
      "IsFollowUpMailSent": false,
      "IsPreadviceMailSent": false,
      "PartyTenantCode": null,
      "SharedRoleCode": null,
      "ConsigneeName": "Zest & Green Marketing Agency,",
      "ConsignorName": "DEMBUYMAA",
      "ORG_CarrierName": "20CUBE LOGISTICS PTY LTD",
      "ORG_SendingAgentName": "20CUBE LOGISTICS SOLUTIONS PRIVATE LIMITED1",
      "ORG_ReceivingAgentName": null,
      "ORG_ControlCustomName": null,
      "ExportCHAName": null,
      "ImportCHAName": null,
      "BuyingHouseAgentName": null,
      "WHCode": null,
      "WHName": null,
      "OrderType": "POR",
      "CustomVarI": null,
      "CustomVarII": null,
      "CustomVarIII": null,
      "CustomVarIV": null,
      "CustomVarV": null,
      "JCT_FK": null,
      "IsBooked": false,
      "OrderPlacedDate": null,
      "CargoReadyDateRequestedDate": null,
      "CargoReadyDateReceivedDate": null,
      "VesselPlanRequestedDate": null,
      "VesselPlanReceivedDate": null,
      "BookedDate": "2025-02-12T06:23:36.687",
      "PlannedCarrierPK": null,
      "PlannedCarrierCode": null,
      "PlannedCarrierName": null,
      "PlannedVesselName": null,
      "PlannedVesselPK": null,
      "PlannedPOL": null,
      "PlannedPOLDesc": null,
      "PlannedPODDesc": null,
      "PlannedPOD": null,
      "PlannedCargoCutOff": null,
      "PlannedBookingCutOff": null,
      "DocumentCutOff": null,
      "CargoReadyDateInitiatedDate": null,
      "SFH_FK": null,
      "FollowUpRefNo": null,
      "PPH_FK": null,
      "PlanningRefNo": null,
      "ContainerNo": null,
      "OriginBranch_FK": "3a77cbf5-d626-4c62-9c30-0392356c9a2f",
      "OriginBranchCode": "MAA",
      "OriginCompany_FK": "58a3ede2-e616-4651-a8ef-7fc311b9fced",
      "OriginCompanyCode": "MAA",
      "DestinationBranch_FK": "32b16ce6-126f-4042-b0d4-d67469d6c61e",
      "DestinationBranchCode": "CMB",
      "DestinationCompany_FK": "25e56ecb-f131-4459-97f1-129705df83ee",
      "DestinationCompanyCode": "CMB",
      "Forwarder_ORG_FK": "f2bc1245-80b5-4c8f-9025-0766dacfc32d",
      "Forwarder_ORG_Code": "20CUBCORP",
      "UIJobAddress": null,
      "UIOrderLine_Forwarder": null,
      "SailingCutoffDate": null,
      "UICustomEntity": null,
      "OrderApprovedDate": null,
      "OrderRejectedDate": null,
      "OrderApprovedRejectedComments": null,
      "ExportForwarder_FK": "416dcf62-bd31-4dca-b3a0-d1c45881f740",
      "ExportForwarder_Code": "OMEGLOMAA",
      "ExportForwarderName": "20CUBE LOGISTICS SOLUTIONS PRIVATE LIMITED1",
      "ImportForwarder_FK": "cd4dac8d-d149-42ef-8e1a-162c9fbf01ae",
      "ImportForwarder_Code": "CLSCONCMB",
      "ImportForwarderName": "20CUBE LOGISTICS (PVT) LTD",
      "OrderApprovalRequestedDate": null,
      "ExportBy": "BRN",
      "ImportBy": "BRN",
      "Origin": null,
      "Destination": null,
      "CountryOfDestination": "LK",
      "CountryOfOrigin": "IN",
      "TraderName": null,
      "TraderCode": null,
      "ORG_Trader_FK": null,
      "SHP_Origin": "INMAA",
      "SHP_Destination": "LKCMB",
      "SHP_OriginName": "Chennai (ex Madras)",
      "SHP_DestinationName": "Colombo",
      "ShipmentStatus": "Sent for Approval",
      "JCT_CustomDecimalI": null,
      "JCT_CustomDecimalII": null,
      "CargoReceiptDate": null,
      "AttachedToBooking": null,
      "CancelledOn": null,
      "CustomGuidI": null,
      "CustomDateI": null,
      "CustomDateII": null,
      "CustomDateIII": null,
      "CustomBitI": false,
      "CustomBitII": false,
      "IsActive": true,
      "OrderLine": [
          {"id":"1", "name":"Palani", "value":"3"}
      ]
  },
  {
      "PK": "e8e1f52a-4cbc-4bf4-ac1a-82a8de665b73",
      "IsValid": true,
      "IsCancelled": false,
      "ORG_Buyer_FK": "c083c734-d2a6-463a-a01d-22b3b01db416",
      "Buyer": "000010070000",
      "BuyerName": "Zest & Green Marketing Agency,",
      "OrderNo": "Thala",
      "FollowUpId": "",
      "PreAdviceId": "",
      "OrderNoSplit": 0,
      "OrderCumSplitNo": "Thala",
      "OrderDate": "2025-02-19T00:00:00",
      "ShpCreatedDate": "2025-01-10T06:03:54.217",
      "OrderStatus": "BOC",
      "GoodsDescription": null,
      "TransportMode": "SEA",
      "ContainerMode": "FCL",
      "ORG_Supplier_FK": "1f2edc90-f552-4547-9e41-a02bc0046bd1",
      "Supplier": "DEMBUYMAA",
      "SupplierName": "DEMBUYMAA",
      "ConfirmNo": "",
      "ConfirmDate": null,
      "FollowUpDate": null,
      "CargoReadyDate": "2025-01-10T00:00:00",
      "RequiredExWorksDate": null,
      "RequiredDeliveryDate": null,
      "InvoiceNo": null,
      "InvoiceDate": null,
      "ExchangeRate": 0,
      "ServiceLevel": null,
      "IncoTerm": "CIF",
      "AdditionalTerms": null,
      "ActualVolume": 0,
      "UnitOfVolume": null,
      "ActualWeight": 0,
      "UnitofWeight": null,
      "Packs": 0,
      "OrderPackType": null,
      "EstimatedExWorksDate": null,
      "EstimatedInStoreDate": null,
      "SHP_FK": "f6b71b64-cc94-4268-99df-613e99279aea",
      "ShipmentNo": "SHP00183339",
      "BRK_FK": null,
      "WayBill": null,
      "MasterWaybill": "987659876",
      "JDA_DeliveryAdress": null,
      "ORA_DeliveryAdress": null,
      "ORG_Carrier_FK": null,
      "CarrierCode": "OBMINTBNE",
      "CarrierName": "",
      "ORG_SendingAgent_FK": "416dcf62-bd31-4dca-b3a0-d1c45881f740",
      "ORG_ReceivingAgent_FK": "cd4dac8d-d149-42ef-8e1a-162c9fbf01ae",
      "ArrivalVoyage": null,
      "GoodsAvailableAt": "INMAA",
      "GoodsAvailableAtDes": "Chennai (ex Madras)",
      "PortOfLoading": "INMAA",
      "PortOfLoadingDes": "Chennai (ex Madras)",
      "PortOfDischarge": "LKCMB",
      "PortOfDischargeDes": "Colombo",
      "GoodsDeliveredTo": "LKCMB",
      "GoodsDeliveredToDes": "Colombo",
      "DepartureVessel": null,
      "DepartureVoyage": null,
      "DepartureVesselCutoffDate": null,
      "IntermediateVessel": null,
      "IntermediateVoyage": null,
      "ArrivalVessel": null,
      "ArrivalIntermediateDate2": null,
      "ArrivalIntermediateDate1": null,
      "EstimatedDepartureDate2": null,
      "EstimatedDepartureDate3": null,
      "EstimatedRecievedDate": null,
      "EstimatedDepartureDate": null,
      "EstimatedArrivalDate": null,
      "EstimatedClearanceCommencedDate": null,
      "EstimatedClearanceFinalizedDate": null,
      "EstimatedUnpackedDate": null,
      "EstimatedPickUp": null,
      "ActualExFactoryDate": null,
      "ActualRecievedDate": null,
      "ActualDepartureDate": null,
      "ActualClearanceCommencedDate": null,
      "ActualArrivalDate": null,
      "ActualClearanceFinalizedDate": null,
      "ActualUnpackedDate": null,
      "ActualPickup": null,
      "ActualInStoreDate": null,
      "OriginCountry": "IN",
      "OrderCurrency": null,
      "ContainerPackType": null,
      "PlannedETD": null,
      "PlannedETA": null,
      "PlannedATD": null,
      "PlannedATA": null,
      "PlannedVessel": null,
      "PlannedVoyage": null,
      "PlannedCarrier": null,
      "ETD": "2023-09-05T00:00:00",
      "ETA": "2023-09-28T00:00:00",
      "ATA": null,
      "ATD": null,
      "Vessel": "test",
      "Voyage": "tesr",
      "Carrier": null,
      "CreatedBy": "ldasarathana@20cube.com",
      "CreatedDateTime": "2025-02-19T10:17:16.943",
      "ModifiedBy": "jprakash@20cube.com",
      "ModifiedDateTime": "2025-03-20T06:31:39.157",
      "StateId": 1080,
      "Source": null,
      "SourceRefKey": null,
      "IsModified": false,
      "IsDeleted": false,
      "Version": null,
      "OrderParentId": null,
      "Communication": null,
      "IsStarred": false,
      "Starred_FK": null,
      "IsShpCreated": true,
      "IsFollowUpIdCreated": false,
      "IsPreAdviceIdCreated": false,
      "POB_FK": null,
      "CustomDate1": null,
      "CustomDate2": null,
      "SendingAgentCode": "OMEGLOMAA",
      "ReceivingAgentCode": "CLSCONCMB",
      "BatchUploadNo": null,
      "CMN_TenantCode": "20CUB",
      "CMN_SharedRoleCode": "3_3",
      "JBS_FK": null,
      "CRT_FK": null,
      "PCFS": null,
      "DCFS": null,
      "Comments": null,
      "ExpectedCargoReadyDate": null,
      "OrderStatusDesc": "Order Booked for Shipment",
      "Status": "",
      "OrderHeaderExtendedPK": null,
      "PAR_ORG_FK": "f2bc1245-80b5-4c8f-9025-0766dacfc32d",
      "PAR_ORG_Code": "20CUBCORP",
      "ORG_ControlCustom_FK": null,
      "ControlCustomCode": null,
      "IsConfirmReqSent": false,
      "PartyType_Code": "FORWARDER",
      "PartyType_FK": "52af4aef-882a-4ae8-990d-4c81d03dfae8",
      "PAR_AccessCode": "3_3",
      "FollowUpSentDate": null,
      "HandoverDate": null,
      "FOBDate": null,
      "ETDPlant": null,
      "FactoryInvoiceNo": null,
      "FactoryPKLNo": null,
      "ImportCHA_Code": null,
      "ExportCHA_Code": null,
      "ExportCHA_FK": null,
      "ImportCHA_FK": null,
      "BuyingHouseAgent_FK": null,
      "BuyingHouseAgent_Code": null,
      "IsFollowUpMailSent": false,
      "IsPreadviceMailSent": false,
      "PartyTenantCode": null,
      "SharedRoleCode": null,
      "ConsigneeName": "Zest & Green Marketing Agency,",
      "ConsignorName": "DEMBUYMAA",
      "ORG_CarrierName": "20CUBE LOGISTICS PTY LTD",
      "ORG_SendingAgentName": "20CUBE LOGISTICS SOLUTIONS PRIVATE LIMITED",
      "ORG_ReceivingAgentName": "20CUBE LOGISTICS (PVT) LTD",
      "ORG_ControlCustomName": null,
      "ExportCHAName": null,
      "ImportCHAName": null,
      "BuyingHouseAgentName": null,
      "WHCode": null,
      "WHName": null,
      "OrderType": "POR",
      "CustomVarI": null,
      "CustomVarII": null,
      "CustomVarIII": null,
      "CustomVarIV": null,
      "CustomVarV": null,
      "JCT_FK": null,
      "IsBooked": false,
      "OrderPlacedDate": null,
      "CargoReadyDateRequestedDate": null,
      "CargoReadyDateReceivedDate": null,
      "VesselPlanRequestedDate": null,
      "VesselPlanReceivedDate": null,
      "BookedDate": "2025-02-19T10:14:02.797",
      "PlannedCarrierPK": null,
      "PlannedCarrierCode": null,
      "PlannedCarrierName": null,
      "PlannedVesselName": null,
      "PlannedVesselPK": null,
      "PlannedPOL": null,
      "PlannedPOLDesc": null,
      "PlannedPODDesc": null,
      "PlannedPOD": null,
      "PlannedCargoCutOff": null,
      "PlannedBookingCutOff": null,
      "DocumentCutOff": null,
      "CargoReadyDateInitiatedDate": null,
      "SFH_FK": null,
      "FollowUpRefNo": null,
      "PPH_FK": null,
      "PlanningRefNo": null,
      "ContainerNo": null,
      "OriginBranch_FK": "3a77cbf5-d626-4c62-9c30-0392356c9a2f",
      "OriginBranchCode": "MAA",
      "OriginCompany_FK": "58a3ede2-e616-4651-a8ef-7fc311b9fced",
      "OriginCompanyCode": "MAA",
      "DestinationBranch_FK": "32b16ce6-126f-4042-b0d4-d67469d6c61e",
      "DestinationBranchCode": "CMB",
      "DestinationCompany_FK": "25e56ecb-f131-4459-97f1-129705df83ee",
      "DestinationCompanyCode": "CMB",
      "Forwarder_ORG_FK": "f2bc1245-80b5-4c8f-9025-0766dacfc32d",
      "Forwarder_ORG_Code": "20CUBCORP",
      "UIJobAddress": null,
      "UIOrderLine_Forwarder": null,
      "SailingCutoffDate": null,
      "UICustomEntity": null,
      "OrderApprovedDate": null,
      "OrderRejectedDate": null,
      "OrderApprovedRejectedComments": null,
      "ExportForwarder_FK": "416dcf62-bd31-4dca-b3a0-d1c45881f740",
      "ExportForwarder_Code": "OMEGLOMAA",
      "ExportForwarderName": "20CUBE LOGISTICS SOLUTIONS PRIVATE LIMITED1",
      "ImportForwarder_FK": "cd4dac8d-d149-42ef-8e1a-162c9fbf01ae",
      "ImportForwarder_Code": "CLSCONCMB",
      "ImportForwarderName": "20CUBE LOGISTICS (PVT) LTD",
      "OrderApprovalRequestedDate": null,
      "ExportBy": "BRN",
      "ImportBy": "BRN",
      "Origin": null,
      "Destination": null,
      "CountryOfDestination": "LK",
      "CountryOfOrigin": "IN",
      "TraderName": null,
      "TraderCode": null,
      "ORG_Trader_FK": null,
      "SHP_Origin": "INMAA",
      "SHP_Destination": "LKCMB",
      "SHP_OriginName": "Chennai (ex Madras)",
      "SHP_DestinationName": "Colombo",
      "ShipmentStatus": "Sent for Approval",
      "JCT_CustomDecimalI": null,
      "JCT_CustomDecimalII": null,
      "CargoReceiptDate": null,
      "AttachedToBooking": null,
      "CancelledOn": null,
      "CustomGuidI": null,
      "CustomDateI": null,
      "CustomDateII": null,
      "CustomDateIII": null,
      "CustomBitI": false,
      "CustomBitII": false,
      "IsActive": true,
      "OrderLine": [
          {"id":"1", "name":"Palani", "value":"3"}
      ]
  },
  {
      "PK": "a68d8a22-32d6-4396-a110-bf90cab59036",
      "IsValid": true,
      "IsCancelled": false,
      "ORG_Buyer_FK": "c083c734-d2a6-463a-a01d-22b3b01db416",
      "Buyer": "000010070000",
      "BuyerName": "Zest & Green Marketing Agency,",
      "OrderNo": "SSATHISH",
      "FollowUpId": "",
      "PreAdviceId": "",
      "OrderNoSplit": 0,
      "OrderCumSplitNo": "SSATHISH",
      "OrderDate": "2025-02-12T00:00:00",
      "ShpCreatedDate": "2025-01-10T06:03:54.217",
      "OrderStatus": "BOC",
      "GoodsDescription": null,
      "TransportMode": "SEA",
      "ContainerMode": "FCL",
      "ORG_Supplier_FK": "1f2edc90-f552-4547-9e41-a02bc0046bd1",
      "Supplier": "DEMBUYMAA",
      "SupplierName": "DEMBUYMAA",
      "ConfirmNo": "",
      "ConfirmDate": null,
      "FollowUpDate": null,
      "CargoReadyDate": "2025-01-10T00:00:00",
      "RequiredExWorksDate": null,
      "RequiredDeliveryDate": null,
      "InvoiceNo": null,
      "InvoiceDate": null,
      "ExchangeRate": 0,
      "ServiceLevel": null,
      "IncoTerm": "CIF",
      "AdditionalTerms": null,
      "ActualVolume": 0,
      "UnitOfVolume": null,
      "ActualWeight": 0,
      "UnitofWeight": null,
      "Packs": 0,
      "OrderPackType": null,
      "EstimatedExWorksDate": null,
      "EstimatedInStoreDate": null,
      "SHP_FK": "f6b71b64-cc94-4268-99df-613e99279aea",
      "ShipmentNo": "SHP00183339",
      "BRK_FK": null,
      "WayBill": null,
      "MasterWaybill": "987659876",
      "JDA_DeliveryAdress": null,
      "ORA_DeliveryAdress": null,
      "ORG_Carrier_FK": null,
      "CarrierCode": "OBMINTBNE",
      "CarrierName": "",
      "ORG_SendingAgent_FK": "416dcf62-bd31-4dca-b3a0-d1c45881f740",
      "ORG_ReceivingAgent_FK": null,
      "ArrivalVoyage": null,
      "GoodsAvailableAt": "INMAA",
      "GoodsAvailableAtDes": "Chennai (ex Madras)",
      "PortOfLoading": "INMAA",
      "PortOfLoadingDes": "Chennai (ex Madras)",
      "PortOfDischarge": "LKCMB",
      "PortOfDischargeDes": "Colombo",
      "GoodsDeliveredTo": "LKCMB",
      "GoodsDeliveredToDes": "Colombo",
      "DepartureVessel": null,
      "DepartureVoyage": null,
      "DepartureVesselCutoffDate": null,
      "IntermediateVessel": null,
      "IntermediateVoyage": null,
      "ArrivalVessel": null,
      "ArrivalIntermediateDate2": null,
      "ArrivalIntermediateDate1": null,
      "EstimatedDepartureDate2": null,
      "EstimatedDepartureDate3": null,
      "EstimatedRecievedDate": null,
      "EstimatedDepartureDate": null,
      "EstimatedArrivalDate": null,
      "EstimatedClearanceCommencedDate": null,
      "EstimatedClearanceFinalizedDate": null,
      "EstimatedUnpackedDate": null,
      "EstimatedPickUp": null,
      "ActualExFactoryDate": null,
      "ActualRecievedDate": null,
      "ActualDepartureDate": null,
      "ActualClearanceCommencedDate": null,
      "ActualArrivalDate": null,
      "ActualClearanceFinalizedDate": null,
      "ActualUnpackedDate": null,
      "ActualPickup": null,
      "ActualInStoreDate": null,
      "OriginCountry": "IN",
      "OrderCurrency": null,
      "ContainerPackType": null,
      "PlannedETD": null,
      "PlannedETA": null,
      "PlannedATD": null,
      "PlannedATA": null,
      "PlannedVessel": null,
      "PlannedVoyage": null,
      "PlannedCarrier": null,
      "ETD": "2023-09-05T00:00:00",
      "ETA": "2023-09-28T00:00:00",
      "ATA": null,
      "ATD": null,
      "Vessel": "test",
      "Voyage": "tesr",
      "Carrier": null,
      "CreatedBy": "ldasarathana@20cube.com",
      "CreatedDateTime": "2025-02-12T06:38:00.373",
      "ModifiedBy": "jprakash@20cube.com",
      "ModifiedDateTime": "2025-03-20T06:31:40.793",
      "StateId": 1080,
      "Source": null,
      "SourceRefKey": null,
      "IsModified": false,
      "IsDeleted": false,
      "Version": null,
      "OrderParentId": null,
      "Communication": null,
      "IsStarred": false,
      "Starred_FK": null,
      "IsShpCreated": true,
      "IsFollowUpIdCreated": false,
      "IsPreAdviceIdCreated": false,
      "POB_FK": null,
      "CustomDate1": null,
      "CustomDate2": null,
      "SendingAgentCode": "OMEGLOMAA",
      "ReceivingAgentCode": null,
      "BatchUploadNo": null,
      "CMN_TenantCode": "20CUB",
      "CMN_SharedRoleCode": "3_3",
      "JBS_FK": null,
      "CRT_FK": null,
      "PCFS": null,
      "DCFS": null,
      "Comments": null,
      "ExpectedCargoReadyDate": null,
      "OrderStatusDesc": "Order Booked for Shipment",
      "Status": "",
      "OrderHeaderExtendedPK": null,
      "PAR_ORG_FK": "f2bc1245-80b5-4c8f-9025-0766dacfc32d",
      "PAR_ORG_Code": "20CUBCORP",
      "ORG_ControlCustom_FK": null,
      "ControlCustomCode": null,
      "IsConfirmReqSent": true,
      "PartyType_Code": "FORWARDER",
      "PartyType_FK": "52af4aef-882a-4ae8-990d-4c81d03dfae8",
      "PAR_AccessCode": "3_3",
      "FollowUpSentDate": null,
      "HandoverDate": null,
      "FOBDate": null,
      "ETDPlant": null,
      "FactoryInvoiceNo": null,
      "FactoryPKLNo": null,
      "ImportCHA_Code": null,
      "ExportCHA_Code": null,
      "ExportCHA_FK": null,
      "ImportCHA_FK": null,
      "BuyingHouseAgent_FK": null,
      "BuyingHouseAgent_Code": null,
      "IsFollowUpMailSent": false,
      "IsPreadviceMailSent": false,
      "PartyTenantCode": null,
      "SharedRoleCode": null,
      "ConsigneeName": "Zest & Green Marketing Agency,",
      "ConsignorName": "DEMBUYMAA",
      "ORG_CarrierName": "20CUBE LOGISTICS PTY LTD",
      "ORG_SendingAgentName": "20CUBE LOGISTICS SOLUTIONS PRIVATE LIMITED1",
      "ORG_ReceivingAgentName": null,
      "ORG_ControlCustomName": null,
      "ExportCHAName": null,
      "ImportCHAName": null,
      "BuyingHouseAgentName": null,
      "WHCode": null,
      "WHName": null,
      "OrderType": "POR",
      "CustomVarI": null,
      "CustomVarII": null,
      "CustomVarIII": null,
      "CustomVarIV": null,
      "CustomVarV": null,
      "JCT_FK": null,
      "IsBooked": false,
      "OrderPlacedDate": null,
      "CargoReadyDateRequestedDate": null,
      "CargoReadyDateReceivedDate": null,
      "VesselPlanRequestedDate": null,
      "VesselPlanReceivedDate": null,
      "BookedDate": "2025-02-12T06:35:31.323",
      "PlannedCarrierPK": null,
      "PlannedCarrierCode": null,
      "PlannedCarrierName": null,
      "PlannedVesselName": null,
      "PlannedVesselPK": null,
      "PlannedPOL": null,
      "PlannedPOLDesc": null,
      "PlannedPODDesc": null,
      "PlannedPOD": null,
      "PlannedCargoCutOff": null,
      "PlannedBookingCutOff": null,
      "DocumentCutOff": null,
      "CargoReadyDateInitiatedDate": null,
      "SFH_FK": null,
      "FollowUpRefNo": null,
      "PPH_FK": null,
      "PlanningRefNo": null,
      "ContainerNo": null,
      "OriginBranch_FK": "3a77cbf5-d626-4c62-9c30-0392356c9a2f",
      "OriginBranchCode": "MAA",
      "OriginCompany_FK": "58a3ede2-e616-4651-a8ef-7fc311b9fced",
      "OriginCompanyCode": "MAA",
      "DestinationBranch_FK": "32b16ce6-126f-4042-b0d4-d67469d6c61e",
      "DestinationBranchCode": "CMB",
      "DestinationCompany_FK": "25e56ecb-f131-4459-97f1-129705df83ee",
      "DestinationCompanyCode": "CMB",
      "Forwarder_ORG_FK": "f2bc1245-80b5-4c8f-9025-0766dacfc32d",
      "Forwarder_ORG_Code": "20CUBCORP",
      "UIJobAddress": null,
      "UIOrderLine_Forwarder": null,
      "SailingCutoffDate": null,
      "UICustomEntity": null,
      "OrderApprovedDate": null,
      "OrderRejectedDate": null,
      "OrderApprovedRejectedComments": null,
      "ExportForwarder_FK": "416dcf62-bd31-4dca-b3a0-d1c45881f740",
      "ExportForwarder_Code": "OMEGLOMAA",
      "ExportForwarderName": "20CUBE LOGISTICS SOLUTIONS PRIVATE LIMITED1",
      "ImportForwarder_FK": "cd4dac8d-d149-42ef-8e1a-162c9fbf01ae",
      "ImportForwarder_Code": "CLSCONCMB",
      "ImportForwarderName": "20CUBE LOGISTICS (PVT) LTD",
      "OrderApprovalRequestedDate": null,
      "ExportBy": "BRN",
      "ImportBy": "BRN",
      "Origin": null,
      "Destination": null,
      "CountryOfDestination": "LK",
      "CountryOfOrigin": "IN",
      "TraderName": null,
      "TraderCode": null,
      "ORG_Trader_FK": null,
      "SHP_Origin": "INMAA",
      "SHP_Destination": "LKCMB",
      "SHP_OriginName": "Chennai (ex Madras)",
      "SHP_DestinationName": "Colombo",
      "ShipmentStatus": "Sent for Approval",
      "JCT_CustomDecimalI": null,
      "JCT_CustomDecimalII": null,
      "CargoReceiptDate": null,
      "AttachedToBooking": null,
      "CancelledOn": null,
      "CustomGuidI": null,
      "CustomDateI": null,
      "CustomDateII": null,
      "CustomDateIII": null,
      "CustomBitI": false,
      "CustomBitII": false,
      "IsActive": true,
      "OrderLine": [
          {"id":"1", "name":"Palani", "value":"3"}
      ]
  },
  {
      "PK": "a60b7481-4b0c-40a3-a6bd-f3fb3cd15344",
      "IsValid": true,
      "IsCancelled": false,
      "ORG_Buyer_FK": "c083c734-d2a6-463a-a01d-22b3b01db416",
      "Buyer": "000010070000",
      "BuyerName": "Zest & Green Marketing Agency,",
      "OrderNo": "YUVARAJ89",
      "FollowUpId": "",
      "PreAdviceId": "",
      "OrderNoSplit": 0,
      "OrderCumSplitNo": "YUVARAJ89",
      "OrderDate": "2025-02-12T00:00:00",
      "ShpCreatedDate": "2025-01-10T06:03:54.217",
      "OrderStatus": "BOC",
      "GoodsDescription": null,
      "TransportMode": "SEA",
      "ContainerMode": "FCL",
      "ORG_Supplier_FK": "1f2edc90-f552-4547-9e41-a02bc0046bd1",
      "Supplier": "DEMBUYMAA",
      "SupplierName": "DEMBUYMAA",
      "ConfirmNo": "",
      "ConfirmDate": null,
      "FollowUpDate": null,
      "CargoReadyDate": "2025-01-10T00:00:00",
      "RequiredExWorksDate": null,
      "RequiredDeliveryDate": null,
      "InvoiceNo": null,
      "InvoiceDate": null,
      "ExchangeRate": 0,
      "ServiceLevel": null,
      "IncoTerm": "CIF",
      "AdditionalTerms": null,
      "ActualVolume": 0,
      "UnitOfVolume": null,
      "ActualWeight": 0,
      "UnitofWeight": null,
      "Packs": 0,
      "OrderPackType": null,
      "EstimatedExWorksDate": null,
      "EstimatedInStoreDate": null,
      "SHP_FK": "f6b71b64-cc94-4268-99df-613e99279aea",
      "ShipmentNo": "SHP00183339",
      "BRK_FK": null,
      "WayBill": null,
      "MasterWaybill": "987659876",
      "JDA_DeliveryAdress": null,
      "ORA_DeliveryAdress": null,
      "ORG_Carrier_FK": null,
      "CarrierCode": "OBMINTBNE",
      "CarrierName": "",
      "ORG_SendingAgent_FK": "416dcf62-bd31-4dca-b3a0-d1c45881f740",
      "ORG_ReceivingAgent_FK": null,
      "ArrivalVoyage": null,
      "GoodsAvailableAt": "INMAA",
      "GoodsAvailableAtDes": "Chennai (ex Madras)",
      "PortOfLoading": "INMAA",
      "PortOfLoadingDes": "Chennai (ex Madras)",
      "PortOfDischarge": "LKCMB",
      "PortOfDischargeDes": "Colombo",
      "GoodsDeliveredTo": "LKCMB",
      "GoodsDeliveredToDes": "Colombo",
      "DepartureVessel": null,
      "DepartureVoyage": null,
      "DepartureVesselCutoffDate": null,
      "IntermediateVessel": null,
      "IntermediateVoyage": null,
      "ArrivalVessel": null,
      "ArrivalIntermediateDate2": null,
      "ArrivalIntermediateDate1": null,
      "EstimatedDepartureDate2": null,
      "EstimatedDepartureDate3": null,
      "EstimatedRecievedDate": null,
      "EstimatedDepartureDate": null,
      "EstimatedArrivalDate": null,
      "EstimatedClearanceCommencedDate": null,
      "EstimatedClearanceFinalizedDate": null,
      "EstimatedUnpackedDate": null,
      "EstimatedPickUp": null,
      "ActualExFactoryDate": null,
      "ActualRecievedDate": null,
      "ActualDepartureDate": null,
      "ActualClearanceCommencedDate": null,
      "ActualArrivalDate": null,
      "ActualClearanceFinalizedDate": null,
      "ActualUnpackedDate": null,
      "ActualPickup": null,
      "ActualInStoreDate": null,
      "OriginCountry": "IN",
      "OrderCurrency": null,
      "ContainerPackType": null,
      "PlannedETD": null,
      "PlannedETA": null,
      "PlannedATD": null,
      "PlannedATA": null,
      "PlannedVessel": null,
      "PlannedVoyage": null,
      "PlannedCarrier": null,
      "ETD": "2023-09-05T00:00:00",
      "ETA": "2023-09-28T00:00:00",
      "ATA": null,
      "ATD": null,
      "Vessel": "test",
      "Voyage": "tesr",
      "Carrier": null,
      "CreatedBy": "ldasarathana@20cube.com",
      "CreatedDateTime": "2025-02-12T06:32:24.073",
      "ModifiedBy": "jprakash@20cube.com",
      "ModifiedDateTime": "2025-03-20T06:31:42.387",
      "StateId": 1080,
      "Source": null,
      "SourceRefKey": null,
      "IsModified": false,
      "IsDeleted": false,
      "Version": null,
      "OrderParentId": null,
      "Communication": null,
      "IsStarred": false,
      "Starred_FK": null,
      "IsShpCreated": true,
      "IsFollowUpIdCreated": false,
      "IsPreAdviceIdCreated": false,
      "POB_FK": null,
      "CustomDate1": null,
      "CustomDate2": null,
      "SendingAgentCode": "OMEGLOMAA",
      "ReceivingAgentCode": null,
      "BatchUploadNo": null,
      "CMN_TenantCode": "20CUB",
      "CMN_SharedRoleCode": "3_3",
      "JBS_FK": null,
      "CRT_FK": null,
      "PCFS": null,
      "DCFS": null,
      "Comments": null,
      "ExpectedCargoReadyDate": null,
      "OrderStatusDesc": "Order Booked for Shipment",
      "Status": "",
      "OrderHeaderExtendedPK": null,
      "PAR_ORG_FK": "f2bc1245-80b5-4c8f-9025-0766dacfc32d",
      "PAR_ORG_Code": "20CUBCORP",
      "ORG_ControlCustom_FK": null,
      "ControlCustomCode": null,
      "IsConfirmReqSent": true,
      "PartyType_Code": "FORWARDER",
      "PartyType_FK": "52af4aef-882a-4ae8-990d-4c81d03dfae8",
      "PAR_AccessCode": "3_3",
      "FollowUpSentDate": null,
      "HandoverDate": null,
      "FOBDate": null,
      "ETDPlant": null,
      "FactoryInvoiceNo": null,
      "FactoryPKLNo": null,
      "ImportCHA_Code": null,
      "ExportCHA_Code": null,
      "ExportCHA_FK": null,
      "ImportCHA_FK": null,
      "BuyingHouseAgent_FK": null,
      "BuyingHouseAgent_Code": null,
      "IsFollowUpMailSent": false,
      "IsPreadviceMailSent": false,
      "PartyTenantCode": null,
      "SharedRoleCode": null,
      "ConsigneeName": "Zest & Green Marketing Agency,",
      "ConsignorName": "DEMBUYMAA",
      "ORG_CarrierName": "20CUBE LOGISTICS PTY LTD",
      "ORG_SendingAgentName": "20CUBE LOGISTICS SOLUTIONS PRIVATE LIMITED1",
      "ORG_ReceivingAgentName": null,
      "ORG_ControlCustomName": null,
      "ExportCHAName": null,
      "ImportCHAName": null,
      "BuyingHouseAgentName": null,
      "WHCode": null,
      "WHName": null,
      "OrderType": "POR",
      "CustomVarI": null,
      "CustomVarII": null,
      "CustomVarIII": null,
      "CustomVarIV": null,
      "CustomVarV": null,
      "JCT_FK": null,
      "IsBooked": false,
      "OrderPlacedDate": null,
      "CargoReadyDateRequestedDate": null,
      "CargoReadyDateReceivedDate": null,
      "VesselPlanRequestedDate": null,
      "VesselPlanReceivedDate": null,
      "BookedDate": "2025-02-12T06:32:53.97",
      "PlannedCarrierPK": null,
      "PlannedCarrierCode": null,
      "PlannedCarrierName": null,
      "PlannedVesselName": null,
      "PlannedVesselPK": null,
      "PlannedPOL": null,
      "PlannedPOLDesc": null,
      "PlannedPODDesc": null,
      "PlannedPOD": null,
      "PlannedCargoCutOff": null,
      "PlannedBookingCutOff": null,
      "DocumentCutOff": null,
      "CargoReadyDateInitiatedDate": null,
      "SFH_FK": null,
      "FollowUpRefNo": null,
      "PPH_FK": null,
      "PlanningRefNo": null,
      "ContainerNo": null,
      "OriginBranch_FK": "3a77cbf5-d626-4c62-9c30-0392356c9a2f",
      "OriginBranchCode": "MAA",
      "OriginCompany_FK": "58a3ede2-e616-4651-a8ef-7fc311b9fced",
      "OriginCompanyCode": "MAA",
      "DestinationBranch_FK": "32b16ce6-126f-4042-b0d4-d67469d6c61e",
      "DestinationBranchCode": "CMB",
      "DestinationCompany_FK": "25e56ecb-f131-4459-97f1-129705df83ee",
      "DestinationCompanyCode": "CMB",
      "Forwarder_ORG_FK": "f2bc1245-80b5-4c8f-9025-0766dacfc32d",
      "Forwarder_ORG_Code": "20CUBCORP",
      "UIJobAddress": null,
      "UIOrderLine_Forwarder": null,
      "SailingCutoffDate": null,
      "UICustomEntity": null,
      "OrderApprovedDate": null,
      "OrderRejectedDate": null,
      "OrderApprovedRejectedComments": null,
      "ExportForwarder_FK": "416dcf62-bd31-4dca-b3a0-d1c45881f740",
      "ExportForwarder_Code": "OMEGLOMAA",
      "ExportForwarderName": "20CUBE LOGISTICS SOLUTIONS PRIVATE LIMITED1",
      "ImportForwarder_FK": "cd4dac8d-d149-42ef-8e1a-162c9fbf01ae",
      "ImportForwarder_Code": "CLSCONCMB",
      "ImportForwarderName": "20CUBE LOGISTICS (PVT) LTD",
      "OrderApprovalRequestedDate": null,
      "ExportBy": "BRN",
      "ImportBy": "BRN",
      "Origin": null,
      "Destination": null,
      "CountryOfDestination": "LK",
      "CountryOfOrigin": "IN",
      "TraderName": null,
      "TraderCode": null,
      "ORG_Trader_FK": null,
      "SHP_Origin": "INMAA",
      "SHP_Destination": "LKCMB",
      "SHP_OriginName": "Chennai (ex Madras)",
      "SHP_DestinationName": "Colombo",
      "ShipmentStatus": "Sent for Approval",
      "JCT_CustomDecimalI": null,
      "JCT_CustomDecimalII": null,
      "CargoReceiptDate": null,
      "AttachedToBooking": null,
      "CancelledOn": null,
      "CustomGuidI": null,
      "CustomDateI": null,
      "CustomDateII": null,
      "CustomDateIII": null,
      "CustomBitI": false,
      "CustomBitII": false,
      "IsActive": true,
      "OrderLine": [
          {"id":"1", "name":"Palani", "value":"3"}
      ]
  }
]

export const BooksData: Book[] = [
  {
    book_id: "BK-7431",
    title: "The Great Adventure",
    author: "John Doe",
    yearPublished: 2021,
    genre: "Adventure",
    chapters: [
      {
        chapter_id: "CH-9123",
        title: "Chapter 1: The Beginning",
        pages: 25,
        summary: "The protagonist embarks on their journey.",
        chapterNumber: 1,
        isImportant: true,
      },
      {
        chapter_id: "CH-8472",
        title: "Chapter 2: Into the Wild",
        pages: 30,
        summary: "The protagonist faces challenges in the wilderness.",
        chapterNumber: 2,
        isImportant: true,
      },
      {
        chapter_id: "CH-3914",
        title: "Chapter 3: The Final Battle",
        pages: 45,
        summary: "The protagonist confronts the antagonist.",
        chapterNumber: 3,
        isImportant: true,
      },
      {
        chapter_id: "CH-5823",
        title: "Chapter 4: The Aftermath",
        pages: 20,
        summary: "The protagonist reflects on the journey.",
        chapterNumber: 4,
        isImportant: false,
      },
    ],
  },
  {
    book_id: "BK-5284",
    title: "Mystery of the Lost City",
    author: "Jane Smith",
    yearPublished: 2019,
    genre: "Mystery",
    chapters: [
      {
        chapter_id: "CH-7521",
        title: "Chapter 1: The Discovery",
        pages: 22,
        summary: "Archaeologists find a hidden city.",
        chapterNumber: 1,
        isImportant: true,
      },
      {
        chapter_id: "CH-6213",
        title: "Chapter 2: Unveiling Secrets",
        pages: 35,
        summary: "The team uncovers the city's secrets.",
        chapterNumber: 2,
        isImportant: true,
      },
      {
        chapter_id: "CH-3749",
        title: "Chapter 3: The Hidden Treasure",
        pages: 40,
        summary: "A treasure is found in the city's ruins.",
        chapterNumber: 3,
        isImportant: true,
      },
    ],
  },
  {
    book_id: "BK-1693",
    title: "The Science of Tomorrow",
    author: "Emily Turner",
    yearPublished: 2023,
    genre: "Science Fiction",
    chapters: [
      {
        chapter_id: "CH-8431",
        title: "Chapter 1: The Invention",
        pages: 18,
        summary: "A scientist invents a time machine.",
        chapterNumber: 1,
        isImportant: true,
      },
      {
        chapter_id: "CH-6512",
        title: "Chapter 2: First Journey",
        pages: 28,
        summary: "The first test of the time machine.",
        chapterNumber: 2,
        isImportant: true,
      },
      {
        chapter_id: "CH-3972",
        title: "Chapter 3: Future Shock",
        pages: 32,
        summary: "The scientist travels to the future.",
        chapterNumber: 3,
        isImportant: true,
      },
      {
        chapter_id: "CH-2794",
        title: "Chapter 4: Returning Home",
        pages: 24,
        summary: "The scientist returns to the present.",
        chapterNumber: 4,
        isImportant: false,
      },
    ],
  },
  {
    book_id: "BK-4827",
    title: "The Chronicles of Eldoria",
    author: "Michael Brown",
    yearPublished: 2020,
    genre: "Fantasy",
    chapters: [
      {
        chapter_id: "CH-9324",
        title: "Chapter 1: The Prophecy",
        pages: 30,
        summary: "A prophecy foretells the rise of a hero.",
        chapterNumber: 1,
        isImportant: true,
      },
      {
        chapter_id: "CH-6832",
        title: "Chapter 2: The Gathering",
        pages: 38,
        summary: "Heroes from across the land gather.",
        chapterNumber: 2,
        isImportant: true,
      },
      {
        chapter_id: "CH-4927",
        title: "Chapter 3: The Battle of Shadows",
        pages: 50,
        summary: "A great battle between light and dark.",
        chapterNumber: 3,
        isImportant: true,
      },
      {
        chapter_id: "CH-2749",
        title: "Chapter 4: The Dawn of Peace",
        pages: 27,
        summary: "Peace is restored to Eldoria.",
        chapterNumber: 4,
        isImportant: false,
      },
    ],
  },
  {
    book_id: "BK-5917",
    title: "The History of Civilizations",
    author: "Sarah Johnson",
    yearPublished: 2018,
    genre: "History",
    chapters: [
      {
        chapter_id: "CH-8423",
        title: "Chapter 1: Ancient Empires",
        pages: 45,
        summary: "An overview of ancient empires.",
        chapterNumber: 1,
        isImportant: true,
      },
      {
        chapter_id: "CH-5732",
        title: "Chapter 2: The Middle Ages",
        pages: 40,
        summary: "Key events during the Middle Ages.",
        chapterNumber: 2,
        isImportant: true,
      },
      {
        chapter_id: "CH-4982",
        title: "Chapter 3: The Renaissance",
        pages: 35,
        summary: "The cultural rebirth of Europe.",
        chapterNumber: 3,
        isImportant: true,
      },
      {
        chapter_id: "CH-6293",
        title: "Chapter 4: The Industrial Revolution",
        pages: 50,
        summary: "The rise of industry and modern society.",
        chapterNumber: 4,
        isImportant: true,
      },
      {
        chapter_id: "CH-7251",
        title: "Chapter 5: The Modern Era",
        pages: 30,
        summary: "Major events of the 20th and 21st centuries.",
        chapterNumber: 5,
        isImportant: true,
      },
    ],
  },
  {
    book_id: "BK-3146",
    title: "Journey Through the Stars",
    author: "Robert Wilson",
    yearPublished: 2022,
    genre: "Science Fiction",
    chapters: [
      {
        chapter_id: "CH-9127",
        title: "Chapter 1: The Launch",
        pages: 20,
        summary: "A spacecraft is launched on a deep space mission.",
        chapterNumber: 1,
        isImportant: true,
      },
      {
        chapter_id: "CH-5382",
        title: "Chapter 2: Alien Encounter",
        pages: 35,
        summary: "The crew encounters an alien species.",
        chapterNumber: 2,
        isImportant: true,
      },
      {
        chapter_id: "CH-4216",
        title: "Chapter 3: The Return Journey",
        pages: 40,
        summary: "The crew returns to Earth with new knowledge.",
        chapterNumber: 3,
        isImportant: true,
      },
    ],
  },
];